import os
from pathlib import Path
from rich.console import Console

console = Console()

# Output folder on your Desktop
OUTPUT_DIR = Path.home() / "Desktop" / "flipper_payloads"

def ensure_dir():
    if not OUTPUT_DIR.exists():
        OUTPUT_DIR.mkdir()

def generate_wifi_grabber(ssid: str, password: str):
    """Generates a Ducky Script to type Wi-Fi credentials."""
    ensure_dir()
    safe_ssid = ssid.replace(" ", "_")
    filename = OUTPUT_DIR / f"wifi_{safe_ssid}.txt"

    # Simple, reliable script for macOS/Windows
    script = f"""
REM Generated by Digital Butler
DELAY 1000
STRING {ssid}
DELAY 500
TAB
DELAY 500
STRING {password}
ENTER
"""
    write_file(filename, script)

def generate_rickroll():
    """Generates a script to open YouTube."""
    ensure_dir()
    filename = OUTPUT_DIR / "rickroll.txt"

    script = """
REM macOS Rickroll
DELAY 1000
GUI SPACE
DELAY 500
STRING Safari
DELAY 500
ENTER
DELAY 1000
STRING https://www.youtube.com/watch?v=dQw4w9WgXcQ
ENTER
"""
    write_file(filename, script)

def generate_terminal_command(command: str):
    """Generates a script to run a specific terminal command."""
    ensure_dir()
    filename = OUTPUT_DIR / "quick_cmd.txt"

    script = f"""
REM macOS Terminal Launcher
DELAY 1000
GUI SPACE
DELAY 500
STRING Terminal
DELAY 500
ENTER
DELAY 1000
STRING {command}
ENTER
"""
    write_file(filename, script)

def write_file(path, content):
    with open(path, "w") as f:
        f.write(content.strip())

    console.print(f"[bold green]✅ Payload forged:[/bold green] {path}")
    console.print("[dim]File ready for Flipper Zero (drag to 'badusb' folder).[/dim]")
